const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');let pw;try{pw=require('playwright');}catch(_){pw=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');}
const root=path.resolve(__dirname,'..'),url='file://'+path.join(root,'dist/renk-duragi-0.5.0.html');let browser;
(async()=>{browser=await pw.chromium.launch({headless:true,executablePath:process.env.RENK_CHROMIUM_PATH||undefined,args:['--no-sandbox','--no-zygote','--disable-dev-shm-usage']});const errors=[],results=[];
 for(const [width,height] of [[320,480],[320,568],[360,640],[360,720],[393,700],[412,732],[390,844],[430,932],[640,360],[844,390]]){
  const p=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:2.75,userAgent:'Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36'});p.on('pageerror',e=>errors.push(e.message));await p.goto(url+'?test=1');await p.getByRole('button',{name:'Otoparka gir'}).tap();
  for(const level of [0,17]){await p.evaluate(i=>ParkingTest.load(i),level);await p.waitForFunction(()=>document.querySelector('#parking').clientHeight>10);const check=await p.evaluate(()=>{const v=document.querySelector('#lot-viewport').getBoundingClientRect(),board=document.querySelector('#parking').getBoundingClientRect();const cars=[...document.querySelectorAll('[data-car]')];const visible=cars.filter(el=>{const r=el.getBoundingClientRect();return r.left>=v.left&&r.right<=v.right&&r.top>=v.top&&r.bottom<=v.bottom&&r.bottom<=innerHeight;});const hit=cars.filter(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.left+r.width/2,r.top+r.height/2)?.closest('[data-car]')===el;});return{screen:[innerWidth,innerHeight],level:ParkingTest.get().index+1,total:cars.length,visible:visible.length,hit:hit.length,carShort:Math.min(...cars.map(el=>Math.min(el.clientWidth,el.clientHeight))),lotHeight:v.height,boardHeight:board.height,docWidth:document.documentElement.scrollWidth,docHeight:document.documentElement.scrollHeight};});
   assert.equal(check.visible,check.total,JSON.stringify(check));assert.equal(check.hit,check.total,'Unreachable car: '+JSON.stringify(check));assert.ok(check.docWidth<=width,'Horizontal page overflow');assert.ok(check.docHeight<=height+1,'Vertical page overflow');assert.ok(check.carShort<50,'Default cars too big');assert.ok(check.lotHeight>=120,JSON.stringify(check));results.push(check);
   const before=await p.evaluate(()=>ParkingTest.get().state);await p.getByRole('button',{name:'Otoparkı yakınlaştır',exact:true}).tap();assert.equal(await p.locator('#overview').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#overlay').isVisible(),false);const min=await p.locator('[data-car]').evaluateAll(els=>Math.min(...els.map(e=>Math.min(e.getBoundingClientRect().width,e.getBoundingClientRect().height))));assert.ok(min>=43.8,'Zoom touch target');await p.getByRole('button',{name:'Otoparkın tamamını göster',exact:true}).tap();assert.equal(await p.locator('#overview').getAttribute('aria-pressed'),'false');assert.deepEqual(await p.evaluate(()=>ParkingTest.get().state),before);
   if(level===17)await p.screenshot({path:path.join(root,`qa/android-${width}x${height}.png`)});
  }
  // An actual tap in the fitted lot dispatches the intended car.
  await p.evaluate(()=>ParkingTest.load(0));await p.locator('[data-car="0"]').tap();await p.waitForFunction(()=>!ParkingTest.get().busy);assert.equal((await p.evaluate(()=>ParkingTest.get())).state.moves,1);
  await p.close();
 }
 const p=await browser.newPage({viewport:{width:360,height:800},isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(e.message));await p.goto(url+'?test=1');await p.getByRole('button',{name:'Otoparka gir'}).tap();for(const height of [640,720,568,800]){await p.setViewportSize({width:360,height});await p.waitForFunction(h=>parseInt(document.documentElement.style.getPropertyValue('--app-height'))===h,height);assert.equal(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),true);}
 // Explicit pixel geometry still works without CSS aspect-ratio support.
 await p.addStyleTag({content:'*{aspect-ratio:auto!important}'});assert.ok(await p.locator('#parking').evaluate(el=>el.clientHeight>150));assert.equal(await p.locator('[data-car]').count(),12);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'qa/android-layout-results.json'),JSON.stringify({version:'0.5.0',results,errors},null,2));console.log('Android layout PASS:',results.length,'lot/screen combinations, actual hit targets, two-way zoom, dynamic resize.');await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1;});
