const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');let pw;try{pw=require('playwright');}catch(_){pw=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));}
const root=path.resolve(__dirname,'..'),url='file://'+path.join(root,'dist/renk-duragi-0.6.0.html');let browser;
(async()=>{
 browser=await pw.chromium.launch({headless:true,executablePath:process.env.RENK_CHROMIUM_PATH||undefined,args:['--no-sandbox','--no-zygote','--disable-dev-shm-usage']});
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[],requests=[];const monitor=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});};monitor(page);
 await page.goto(url+'?test=1');await page.getByRole('button',{name:'Otoparka gir'}).tap();
 const tap=async id=>{await page.locator(`[data-car="${id}"]`).tap();await page.waitForFunction(()=>!ParkingTest.get().busy);};
 await tap(1);assert.equal((await page.evaluate(()=>ParkingTest.get())).state.moves,0);assert.equal(await page.locator('.obstacle').count(),1);await tap(0);assert.equal(await page.locator('[data-bay-car="0"] [data-seat]').count(),4);
 const saved=await page.evaluate(()=>ParkingTest.get().state);await page.reload();assert.deepEqual(await page.evaluate(()=>ParkingTest.get().state),saved);await tap(2);await tap(3);assert.equal(await page.locator('#app').evaluate(el=>el.classList.contains('jammed')),true);await page.screenshot({path:path.join(root,'qa/v04-jam.png'),fullPage:true});
 await page.getByRole('button',{name:'Geri al',exact:true}).tap();assert.equal(await page.locator('#app').evaluate(el=>el.classList.contains('jammed')),false);await page.getByRole('button',{name:'İpucu',exact:true}).tap();assert.equal(await page.locator('.car.hinted').count(),1);await tap(1);assert.equal((await page.evaluate(()=>ParkingTest.get())).state.head,12);
 const outcomes=[];
 for(let i=0;i<(process.env.RENK_SMOKE?1:18);i++){await page.evaluate(i=>ParkingTest.load(i),i);const solution=await page.evaluate(()=>ParkingTest.solve());assert.ok(solution.path);for(const id of solution.path)await tap(id);assert.equal(await page.locator('#finish-card h2').innerText(),'Park açıldı!');assert.equal(await page.evaluate(()=>ParkingTest.E.won(ParkingTest.levels[ParkingTest.get().index],ParkingTest.get().state)),true);outcomes.push({level:i+1,moves:(await page.evaluate(()=>ParkingTest.get())).state.moves});console.log('Solved level',i+1);}
 await page.evaluate(()=>ParkingTest.load(17));
 for(const width of [320,360,390,430,1280]){await page.setViewportSize({width,height:width===320?568:width===360?740:width===430?932:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'Otoparkı yakınlaştır',exact:true}).click();const targets=await page.locator('[data-car]').evaluateAll(els=>els.map(el=>({w:el.getBoundingClientRect().width,h:el.getBoundingClientRect().height})));assert.ok(targets.every(r=>Math.min(r.w,r.h)>=43.8),'Zoom car touch target must be >=44px');await page.getByRole('button',{name:'Otoparkın tamamını göster',exact:true}).click();if(width===390)assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),'Game should fit ordinary phone');await page.screenshot({path:path.join(root,`qa/v04-${width}.png`),fullPage:true});}
 await page.getByRole('button',{name:'Yolcu sırasının tamamı'}).click();assert.equal(await page.locator('.queue-list .person').count(),120);await page.keyboard.press('Escape');assert.equal(await page.locator('#overlay').isVisible(),false);await page.getByRole('button',{name:'Otoparkı yakınlaştır',exact:true}).click();assert.equal(await page.locator('#overview').getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Otoparkın tamamını göster',exact:true}).click();assert.equal(await page.locator('#overview').getAttribute('aria-pressed'),'false');
 const beforeMood=await page.evaluate(()=>ParkingTest.get().state);await page.evaluate(()=>ParkingTest.moods(60000));assert.ok(await page.locator('.mood-angry').count()>0);assert.ok(await page.locator('.mood-toilet').count()>0);assert.deepEqual(await page.evaluate(()=>ParkingTest.get().state),beforeMood);
 const bad=await browser.newPage();monitor(bad);await bad.addInitScript(()=>localStorage.setItem('renk-parking-v041',JSON.stringify({version:4,index:0,log:[{type:'send',id:999}],seen:true})));await bad.goto(url+'?test=1');assert.equal((await bad.evaluate(()=>ParkingTest.get())).state.moves,0);await bad.close();
 const motion=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});monitor(motion);await motion.goto(url+'?test=1&motion=1');await motion.getByRole('button',{name:'Otoparka gir'}).tap();
 await motion.evaluate(()=>{ParkingTest.dispatch(0);ParkingTest.dispatch(2);ParkingTest.dispatch(3);ParkingTest.dispatch(0);});let s=(await motion.evaluate(()=>ParkingTest.get())).state;assert.equal(s.moves,3);assert.equal(s.bays.filter(Boolean).length,3);assert.equal(await motion.locator('#overlay').isVisible(),false);assert.equal(await motion.locator('[data-car="1"]').isEnabled(),true);assert.equal(await motion.locator('[data-car="1"]').evaluate(el=>getComputedStyle(el).opacity),'1');await motion.waitForTimeout(350);assert.equal((await motion.evaluate(()=>ParkingTest.get())).state.bays.filter(b=>b?.phase==='driving').length,3);
 await motion.getByRole('button',{name:'Geri al',exact:true}).tap();const afterUndo=await motion.evaluate(()=>ParkingTest.get().state);assert.equal(afterUndo.moves,2);assert.equal(afterUndo.bays.filter(Boolean).length,2);await motion.waitForTimeout(3500);assert.deepEqual(await motion.evaluate(()=>ParkingTest.get().state),afterUndo);
 await motion.evaluate(()=>ParkingTest.load(0));await motion.locator('[data-car="0"]').tap();await motion.waitForFunction(()=>!ParkingTest.get().state.exiting.includes(0));await motion.locator('[data-car="1"]').tap();await motion.waitForFunction(()=>ParkingTest.get().state.head>=1,{},{timeout:20000});await motion.waitForFunction(()=>document.querySelector('.fly-person'));assert.ok(await motion.locator('.fly-person').count()>0);await motion.locator('[data-car="2"]').tap();s=(await motion.evaluate(()=>ParkingTest.get())).state;assert.equal(s.moves,3);assert.ok(s.head<8);assert.ok(s.bays.some(b=>b?.id===2&&b.phase==='driving'));await motion.screenshot({path:path.join(root,'qa/v04-boarding.png'),fullPage:true});
 // Reset during live boarding cancels every old animation callback.
 await motion.evaluate(()=>ParkingTest.load(1));const reset=await motion.evaluate(()=>ParkingTest.get().state);await motion.waitForTimeout(3500);assert.deepEqual(await motion.evaluate(()=>ParkingTest.get().state),reset);assert.equal(await motion.locator('.ghost-car,.fly-person').count(),0);
 // A saved in-flight command is restored as a settled, valid position.
 await motion.evaluate(()=>{ParkingTest.load(0);ParkingTest.dispatch(0);ParkingTest.dispatch(2);});await motion.reload();s=(await motion.evaluate(()=>ParkingTest.get())).state;assert.equal(s.moves,2);assert.equal(s.bays.filter(Boolean).length,2);assert.ok(s.bays.filter(Boolean).every(b=>b.phase==='waiting'));
 const reduced=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});monitor(reduced);await reduced.goto(url+'?test=1&motion=1');await reduced.getByRole('button',{name:'Otoparka gir'}).click();await reduced.evaluate(()=>ParkingTest.dispatch(0));await reduced.waitForFunction(()=>!ParkingTest.get().busy);assert.equal((await reduced.evaluate(()=>ParkingTest.get())).state.moves,1);
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);fs.writeFileSync(path.join(root,process.env.RENK_SMOKE?'qa/browser-smoke-results.json':'qa/browser-results.json'),JSON.stringify({version:'0.6.0',outcomes,viewports:[320,360,390,430,1280],errors,externalRequests:requests.length,checks:['physical blockers','full-bay deadlock','18 live winning paths','44px zoom targets','single-screen phone','queue + playable fit/zoom','cosmetic moods','concurrent sends','no input dimming','natural motion timing','dispatch while boarding','cancel undo + reset','resume in flight','corrupt log','reduced motion']},null,2));console.log('Browser PASS:',outcomes.length,'levels, concurrency, boarding, cancellation, 5 viewports');await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1;});
