const test=require('node:test'),assert=require('node:assert/strict'),E=require('../src/engine.js'),levels=require('../src/data.cjs');
function invariant(l,s){const located=[...s.parked,...s.departed,...s.bays.filter(Boolean).map(b=>b.id)];assert.equal(new Set(located).size,l.cars.length);assert.equal(located.length,l.cars.length);assert.equal(s.moves,l.cars.length-s.parked.length);assert.ok(s.exiting.every(id=>s.bays.some(b=>b?.id===id&&b.phase==='driving')));const boarded=[0,0,0,0];for(const id of s.departed){const c=E.car(l,id);boarded[c.color]+=c.capacity;}for(const b of s.bays.filter(Boolean)){const c=E.car(l,b.id);assert.ok(b.filled>=0&&b.filled<=c.capacity);boarded[c.color]+=b.filled;}assert.deepEqual(boarded,[0,1,2,3].map(c=>l.queue.slice(0,s.head).filter(v=>v===c).length));}
function apply(l,s,type,id){const r=E.transition(l,s,{type,id});assert.ok(r.ok,JSON.stringify({type,id,reason:r.reason}));invariant(l,r.state);return r.state;}
function settleLive(l,s){for(const b of [...s.bays].filter(Boolean)){if(b.phase==='driving'){if(s.exiting.includes(b.id))s=apply(l,s,'clear',b.id);s=apply(l,s,'arrive',b.id);}else if(b.phase==='leaving')s=apply(l,s,'leave',b.id);}let slot;while((slot=E.nextBoard(l,s))>=0){const id=s.bays[slot].id;s=apply(l,s,'board',id);if(s.bays[slot].phase==='leaving')s=apply(l,s,'leave',id);}return s;}
test('Physical blockage persists until the front car clears the lot',()=>{const l=levels[0];let s=E.initial(l);assert.deepEqual(E.blockers(l,s,1),[0]);s=apply(l,s,'send',0);assert.equal(E.transition(l,s,{type:'send',id:1}).reason,'blocked');s=apply(l,s,'clear',0);assert.deepEqual(E.blockers(l,s,1),[]);assert.ok(E.transition(l,s,{type:'send',id:1}).ok);});
test('Concurrent departures reserve real bays; duplicate and fourth sends fail',()=>{const l=levels[0];let s=E.initial(l);for(const id of [0,2,3])s=apply(l,s,'send',id);assert.equal(s.bays.filter(Boolean).length,3);assert.equal(E.transition(l,s,{type:'send',id:0}).reason,'missing');s=apply(l,s,'clear',0);assert.equal(E.transition(l,s,{type:'send',id:1}).reason,'full');assert.equal(E.deadlocked(l,s),false);s=settleLive(l,s);assert.equal(E.deadlocked(l,s),true);assert.equal(s.head,0);});
test('FIFO, actual arrival, visible seats, delayed bay release',()=>{const l=levels[0];let s=apply(l,E.initial(l),'send',0);s=apply(l,s,'clear',0);s=apply(l,s,'send',1);assert.equal(E.nextBoard(l,s),-1);assert.equal(E.transition(l,s,{type:'board',id:1}).ok,false);s=apply(l,s,'clear',1);s=apply(l,s,'arrive',1);for(let i=0;i<4;i++)s=apply(l,s,'board',1);assert.equal(s.bays[1].phase,'leaving');assert.equal(s.bays.filter(Boolean).length,2);assert.equal(s.departed.length,0);assert.equal(E.transition(l,s,{type:'board',id:1}).ok,false);s=apply(l,s,'leave',1);assert.equal(s.bays[1],null);assert.equal(s.departed.length,1);assert.equal(E.nextBoard(l,s),-1);s=apply(l,s,'arrive',0);assert.equal(E.nextBoard(l,s),0);});
test('Matching cars board in dispatch order even when the second arrives first',()=>{const l=levels[0];let s=E.initial(l);s.head=8;for(const id of [2,3])s=E.transition(l,s,{type:'send',id}).state;s=E.transition(l,s,{type:'clear',id:3}).state;s=E.transition(l,s,{type:'arrive',id:3}).state;assert.equal(E.nextBoard(l,s),-1);s=E.transition(l,s,{type:'clear',id:2}).state;s=E.transition(l,s,{type:'arrive',id:2}).state;assert.equal(s.bays[E.nextBoard(l,s)].id,2);});
test('Commands replay exactly; corrupt commands are rejected without mutation',()=>{const l=levels[0],log=[{type:'send',id:0},{type:'clear',id:0},{type:'arrive',id:0},{type:'send',id:1}];const s=E.replay(l,log),before=JSON.stringify(s);assert.equal(E.transition(l,s,{type:'leave',id:0}).ok,false);assert.equal(JSON.stringify(s),before);assert.throws(()=>E.replay(l,[{type:'send',id:999}]));assert.throws(()=>E.replay(l,[{type:'arrive',id:0}]));assert.deepEqual(E.replay(l,log.slice(0,3)).parked,E.initial(l).parked.filter(id=>id!==0));});
test('Independent swept-grid collision oracle agrees for sampled layouts and all directions',()=>{let seed=44;const rng=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);for(const l of levels)for(let run=0;run<70;run++){const s=E.initial(l);if(run)s.parked=s.parked.filter(()=>rng()<.65);for(const id of s.parked){const c=E.car(l,id),found=new Set(),cells=new Map(),delta={N:[0,-1],S:[0,1],E:[1,0],W:[-1,0]}[c.dir];for(const other of s.parked){if(other===id)continue;const b=E.car(l,other);for(let x=b.x;x<b.x+b.w;x++)for(let y=b.y;y<b.y+b.h;y++)cells.set(x+','+y,other);}for(let d=1;d<=Math.max(l.width,l.height);d++)for(let x=c.x+delta[0]*d;x<c.x+delta[0]*d+c.w;x++)for(let y=c.y+delta[1]*d;y<c.y+delta[1]*d+c.h;y++)if(cells.has(x+','+y))found.add(cells.get(x+','+y));assert.deepEqual(E.blockers(l,s,id).sort((a,b)=>a-b),[...found].sort((a,b)=>a-b));}}});
test('Malformed levels fail validation',()=>{const l=E.copy(levels[0]);l.cars[1].x=l.cars[0].x;l.cars[1].y=l.cars[0].y;l.queue.pop();assert.ok(E.validate(l).includes('overlap'));assert.ok(E.validate(l).includes('passenger balance'));});
for(const l of levels)test('Level '+l.id+': large balanced lot, live and solver witness, real deadlock',()=>{assert.deepEqual(E.validate(l),[]);assert.ok(l.cars.length>=12);assert.ok(l.queue.length>=48);let sync=E.initial(l),live=E.initial(l);for(const id of l.solution){const r=E.step(l,sync,id);assert.ok(r.ok);sync=r.state;live=settleLive(l,apply(l,live,'send',id));invariant(l,sync);assert.deepEqual(live,sync);}assert.ok(E.won(l,live));assert.ok(E.solve(l).path);let trap=E.initial(l);for(const id of l.trap)trap=E.step(l,trap,id).state;assert.ok(E.deadlocked(l,trap));assert.equal(E.solve(l,trap,100).path,null);});
