const assert=require('node:assert/strict'),path=require('node:path');let pw;try{pw=require('playwright');}catch(_){pw=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');}
const root=path.resolve(__dirname,'..'),url='file://'+path.join(root,'dist/renk-duragi-0.7.0.html');let browser;
(async()=>{
 browser=await pw.chromium.launch({headless:true,executablePath:process.env.RENK_CHROMIUM_PATH||undefined,args:['--no-sandbox','--no-zygote','--disable-dev-shm-usage']});const errors=[],requests=[],watch=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});};
 const p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});watch(p);await p.goto(url+'?test=1');await p.getByRole('button',{name:'Otoparka gir'}).tap();assert.equal(await p.evaluate(()=>ParkingTest.levels.length),500);
 const themes=[];for(const [i,name] of [[0,'Mahalle'],[20,'Sahil'],[40,'Pazar yeri'],[60,'Festival'],[80,'Havaalanı']]){await p.evaluate(i=>ParkingTest.load(i),i);assert.ok((await p.locator('#district-name').innerText()).startsWith(name));themes.push(await p.locator('#parking').evaluate(el=>getComputedStyle(el).backgroundColor));const actual=await p.locator('#queue .person').evaluateAll(els=>els.map(e=>+e.dataset.color));assert.deepEqual(actual,await p.evaluate(n=>ParkingTest.levels[ParkingTest.get().index].queue.slice(0,n),actual.length),'Reset must show the new level colors');}assert.equal(new Set(themes).size,5);
 await p.locator('#level-menu').tap();assert.equal(await p.locator('.district-card').count(),1);assert.equal(await p.locator('[data-level]').count(),20);await p.locator('#chapter-select').selectOption('0');await p.screenshot({path:path.join(root,'qa/city-map.png')});await p.locator('[data-level="18"]').tap();assert.equal((await p.evaluate(()=>ParkingTest.get())).index,18);
 const routeIndices=await p.evaluate(()=>ParkingTest.levels.flatMap((l,i)=>l.legacyId>=19&&l.legacyId<=24?[i]:[]));for(const i of routeIndices){await p.evaluate(i=>ParkingTest.load(i),i);const ids=await p.evaluate(()=>ParkingTest.levels[ParkingTest.get().index].solution);for(const id of ids){await p.locator(`[data-car="${id}"]`).tap();await p.waitForFunction(()=>!ParkingTest.get().busy);}await p.waitForFunction(()=>!document.querySelector('#finish-card').hidden);assert.equal(await p.locator('#finish-card h2').innerText(),'Park açıldı!');assert.equal(await p.locator('#overlay').isVisible(),false);assert.equal(await p.locator('#app').evaluate(el=>el.inert),false);assert.equal(await p.locator('#cars button').count(),0);if(i===routeIndices[0]){await p.screenshot({path:path.join(root,'qa/experience-win.png')});await p.locator('#finish-card [data-action="next"]').tap();assert.equal((await p.evaluate(()=>ParkingTest.get())).index,i+1);}console.log('Special route PASS',i+1);}
 await p.setViewportSize({width:320,height:480});await p.waitForTimeout(80);assert.ok(await p.locator('#finish-card').evaluate(el=>{const r=el.getBoundingClientRect(),v=document.querySelector('#lot-viewport').getBoundingClientRect();return r.top>=v.top&&r.bottom<=v.bottom;}),'Finish card must fit a short phone');assert.ok(await p.locator('#finish-card .primary').evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('button')===el;}));await p.screenshot({path:path.join(root,'qa/experience-win-short.png')});await p.reload();assert.equal(await p.locator('#finish-card').isVisible(),true);await p.locator('#finish-card [data-action="levels"]').first().tap();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem(ParkingTest.storageKey)).completedUids.filter(id=>['lot-19','lot-20','lot-21','lot-22','lot-23','lot-24'].includes(id)).length),6);await p.close();
 const m=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});watch(m);await m.goto(url+'?test=1&motion=1');await m.getByRole('button',{name:'Otoparka gir'}).tap();await m.locator('#sound').tap();await m.locator('[data-car="0"]').tap();assert.ok((await m.evaluate(()=>ParkingTest.get())).audioActive>0);await m.locator('#sound').tap();assert.equal((await m.evaluate(()=>ParkingTest.get())).audioActive,0);
 await m.waitForFunction(()=>document.querySelector('.road-open'),{},{timeout:15000});assert.equal((await m.evaluate(()=>ParkingTest.get())).state.exiting.includes(0),false);await m.waitForFunction(()=>!ParkingTest.get().busy);
 await m.evaluate(()=>window.retainedPerson=document.querySelector('#queue [data-person="1"]'));await m.locator('[data-car="1"]').tap();await m.waitForFunction(()=>document.querySelector('.door-light'),{},{timeout:15000});await m.screenshot({path:path.join(root,'qa/experience-door.png')});await m.waitForFunction(()=>document.querySelector('.queue-walking')?.getAnimations().length,{},{timeout:15000});
 assert.ok(await m.evaluate(()=>window.retainedPerson===document.querySelector('#queue [data-person="1"]')),'Passengers keep identity while advancing');
 const turn=await m.locator('.queue-walking').evaluateAll(els=>els.map(el=>el.getAnimations()[0]?.effect.getKeyframes()).find(k=>k?.length>2));assert.ok(turn?.length>=12,'Turns must follow the curved rail instead of a straight jump');
 await m.locator('#speed').tap();await m.locator('#speed').tap();const rates=await m.locator('.queue-walking').evaluateAll(els=>els.flatMap(el=>el.getAnimations().map(a=>a.playbackRate)));assert.ok(rates.length>0);assert.ok(rates.every(r=>r===2),'Queue walk follows fast speed');
 await m.locator('#undo').tap();const stable=await m.evaluate(()=>ParkingTest.get().state);await m.waitForTimeout(1600);assert.deepEqual(await m.evaluate(()=>ParkingTest.get().state),stable);assert.equal(await m.locator('.queue-walking,.fly-person,.door-light,.road-open').count(),0);
 await m.evaluate(()=>ParkingTest.load(7));await m.screenshot({path:path.join(root,'qa/experience-overview.png')});await m.close();assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);console.log('Experience PASS: six playable routes, five districts, inline finish/persistence, live queue turns, speed, cancellation, sound toggle; no external requests');await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1;});
