const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');let pw;try{pw=require('playwright');}catch(_){pw=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');}
const root=path.resolve(__dirname,'..'),url='file://'+path.join(root,'dist/renk-duragi-0.5.2.html');let browser;
(async()=>{browser=await pw.chromium.launch({headless:true,executablePath:process.env.RENK_CHROMIUM_PATH||undefined,args:['--no-sandbox','--no-zygote','--disable-dev-shm-usage']});const errors=[],p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(e.message));await p.goto(url+'?test=1');await p.getByRole('button',{name:'Otoparka gir'}).tap();
 const crowd=async()=>{const a=await p.locator('#queue .person').evaluateAll(els=>els.map(el=>({id:+el.dataset.person,color:+el.dataset.color}))),expected=await p.evaluate(()=>{const s=ParkingTest.get();return ParkingTest.levels[s.index].queue.slice(s.state.head,s.state.head+document.querySelectorAll('#queue .person').length).map((color,i)=>({color,id:s.state.head+i}));});assert.deepEqual(a,expected);};await crowd();assert.ok(await p.locator('#queue .person').count()>=27);assert.equal(await p.locator('#cars .direction-arrow').count(),12);assert.equal(await p.locator('#cars .vehicle-roof').count(),12);
 const before=await p.evaluate(()=>ParkingTest.get().state);for(const [value,label] of [[1.3,'Normal'],[2,'Hızlı'],[1,'Sakin']]){await p.locator('#speed').tap();assert.equal((await p.evaluate(()=>ParkingTest.get())).speed,value);assert.equal(await p.locator('#speed small').innerText(),label);assert.deepEqual(await p.evaluate(()=>ParkingTest.get().state),before);}
 for(const id of [0,1]){await p.locator(`[data-car="${id}"]`).tap();await p.waitForFunction(()=>!ParkingTest.get().busy);await crowd();if(id===0){assert.equal(await p.locator('[data-bay-car="0"] [data-seat]').count(),4);assert.equal(await p.locator('[data-bay-car="0"] .vehicle-roof').count(),0);}}
 const oldState=await p.evaluate(()=>ParkingTest.get().state);await p.reload();assert.deepEqual(await p.evaluate(()=>ParkingTest.get().state),oldState);await crowd();await p.evaluate(()=>ParkingTest.load(17));assert.ok(await p.locator('#queue .person').count()>=27);await crowd();
 for(const size of [{width:320,height:568},{width:360,height:640},{width:390,height:844}]){await p.setViewportSize(size);await p.waitForTimeout(80);await crowd();assert.ok(await p.locator('#queue-info').evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('#queue-info')===el;}),'Crowd must not cover queue button');assert.deepEqual(await p.locator('.crowd-ground').evaluate(el=>{const b=el.getBoundingClientRect();return [...el.querySelectorAll('.person')].map(e=>{const r=e.getBoundingClientRect();return {id:e.dataset.person,x:r.left-b.left,y:r.top-b.top,w:r.width,h:r.height,bw:b.width,bh:b.height};}).filter(r=>r.x < -1 || r.y < -1 || r.x+r.w>r.bw+1 || r.y+r.h>r.bh+1);}),[],'Crowd stays inside scene');}
 const count=await p.locator('#queue .person').count();assert.deepEqual(await p.locator('#queue .queue-number').allTextContents(),Array.from({length:count},(_,i)=>String(i+1)));
 const boxes=await p.locator('#queue .person').evaluateAll(els=>els.map(e=>{const b=e.getBoundingClientRect();return {left:b.left,right:b.right,top:b.top,bottom:b.bottom};}));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert.ok(a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top,'Passengers must not overlap');}
 const stable=await p.evaluate(()=>ParkingTest.get().state);for(const ms of [30000,60000,120000]){await p.evaluate(ms=>ParkingTest.moods(ms),ms);assert.ok(await p.locator('#queue .mood-bubble:not([hidden])').count()<=1);assert.equal(await p.locator('#queue .next-passenger .mood-bubble:not([hidden])').count(),0);assert.deepEqual(await p.evaluate(()=>ParkingTest.get().state),stable);}
 await p.locator('#queue-info').tap();assert.deepEqual(await p.locator('.queue-list .queue-number').allTextContents(),Array.from({length:120},(_,i)=>String(i+1)));assert.equal(await p.locator('.queue-list .mood-bubble:not([hidden])').count(),0);await p.locator('#close-modal').tap();
 await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(root,'qa/scene-overview.png')});await p.close();
 const m=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});m.on('pageerror',e=>errors.push(e.message));await m.goto(url+'?test=1&motion=1');await m.getByRole('button',{name:'Otoparka gir'}).tap();await m.locator('[data-car="0"]').tap();await m.waitForFunction(()=>document.querySelector('.ghost-car')?.getAnimations().length);assert.equal(await m.locator('.ghost-car').first().evaluate(el=>el.getAnimations()[0].playbackRate),1);
 await m.locator('#speed').tap();assert.equal(await m.locator('.ghost-car').first().evaluate(el=>el.getAnimations()[0].playbackRate),1.3);await m.locator('#speed').tap();assert.equal(await m.locator('.ghost-car').first().evaluate(el=>el.getAnimations()[0].playbackRate),2);await m.waitForFunction(()=>!ParkingTest.get().busy);assert.equal((await m.evaluate(()=>ParkingTest.get())).state.moves,1);
 await m.reload();assert.equal((await m.evaluate(()=>ParkingTest.get())).speed,2);assert.equal(await m.locator('#speed small').innerText(),'Hızlı');await m.locator('[data-car="1"]').tap();await m.waitForFunction(()=>document.querySelector('.fly-person'),{},{timeout:15000});assert.equal(await m.locator('.fly-person').evaluate(el=>el.getAnimations()[0].playbackRate),2);await m.locator('#speed').tap();assert.equal((await m.evaluate(()=>ParkingTest.get())).speed,1);assert.equal(await m.locator('.fly-person').evaluate(el=>el.getAnimations()[0].playbackRate),1);await m.setViewportSize({width:360,height:640});await m.waitForTimeout(60);assert.equal(await m.locator('#queue .walking-out').count(),1,'Resizing must keep walking passenger hidden');await m.screenshot({path:path.join(root,'qa/scene-boarding.png')});await m.evaluate(()=>ParkingTest.load(0));
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'qa/scene-speed-results.json'),JSON.stringify({version:'0.5.2',errors,checks:['Single-file crowd in real FIFO order','queue after boarding and reload','roof/seat rendering','three-speed cycle without state changes','live vehicle playback rate','live boarding playback rate','fast-speed persistence','crowd containment','touchable queue control']},null,2));console.log('Scene / speed PASS');await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1;});
