const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'..');
const E=require('../src/engine.js'),levels=require('../src/levels.js');
const evidence=levels.map(l=>{const issues=E.validate(l);if(issues.length)throw Error(l.id+': '+issues);const solution=E.solve(l),analysis=E.analyze(l);if(!solution.path||!analysis.trap)throw Error('Both solution and trap required: '+l.id);return {level:l.id,cars:l.cars.length,passengers:l.queue.length,solution:solution.path,...analysis};});
const read=name=>fs.readFileSync(path.join(root,'src',name),'utf8');let html=read('index.html');
html=html.replace('<link rel="stylesheet" href="style.css">',()=>'<style>\n'+read('style.css')+'\n</style>');
for(const name of ['engine','levels','app'])html=html.replace('<script src="'+name+'.js"></script>',()=>'<script>\n'+read(name+'.js')+'\n</script>');
fs.mkdirSync(path.join(root,'dist'),{recursive:true});fs.mkdirSync(path.join(root,'qa'),{recursive:true});
fs.writeFileSync(path.join(root,'dist/renk-duragi-0.3.0.html'),html);
fs.writeFileSync(path.join(root,'qa/solutions.json'),JSON.stringify(evidence,null,2)+'\n');
console.log(evidence.map(v=>({level:v.level,cars:v.cars,randomWin:Number(v.randomWin.toFixed(3)),deadEnds:v.deadEnds})));console.log('Built dist/renk-duragi-0.3.0.html');
