(function(){
'use strict';
const E=window.ParkingEngine,levels=window.PARKING_LEVELS,$=id=>document.getElementById(id),params=new URLSearchParams(location.search);
const KEY='renk-parking-v070',names=['Kırmızı','Mavi','Sarı','Mor'],colors=['#ff5063','#4295ff','#ffcc43','#a174ff'],angles={N:0,E:90,S:180,W:270},directions={N:'yukarı',E:'sağa',S:'aşağı',W:'sola'};
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,testMode=params.has('test'),fast=testMode&&!params.has('motion');
let index=0,state,log=[],completed=[],seen=false,speed=1,sound=false,epoch=0,boarding=false,focused=null,audioContext,queueHead=-1,levelStarted=Date.now(),moodOffset=0,roadTail=Promise.resolve();
let zoomed=false,layoutFrame=0,svgSerial=0,queueMotion=Promise.resolve(),crowdLayout=null,crowdLevel=-1,celebrated=false,mapPage=0,nativePaused=false;
const queueAnimations=new Set(),audioNodes=new Set();
const districts=[{id:"mahalle",name:"Mahalle",icon:"⌂",start:0,end:4,desc:"Sakin sokaklar, ilk yolculuklar"},{id:"sahil",name:"Sahil",icon:"≈",start:4,end:8,desc:"Deniz kıyısında bir mola"},{id:"pazar",name:"Pazar yeri",icon:"▥",start:8,end:12,desc:"Renkli tezgâhlar, hareketli sokaklar"},{id:"festival",name:"Festival",icon:"♫",start:12,end:15,desc:"Şehrin buluşma noktası"},{id:"havalimani",name:"Havaalanı",icon:"✈",start:15,end:18,desc:"Son çağrı, büyük buluşma"}];
const district=()=>districts.find(d=>d.id===level().district)||districts.find(d=>index>=d.start&&index<d.end)||districts[0];
const chapters=Array.from({length:Math.ceil(levels.length/20)},(_,i)=>{const start=i*20,end=Math.min(levels.length,start+20),d=districts[i%5];return {start,end,label:d.name+' · '+(start+1)+'–'+end,district:d.id};});
const pageFor=i=>Math.floor(i/20);
const speedModes=[{value:1,label:'Sakin',icon:'◷'},{value:1.3,label:'Normal',icon:'▷'},{value:2,label:'Hızlı',icon:'»'}];
const animations=new Set(),departures=new Set(),level=()=>levels[index],duration=n=>fast||reduced?1:n;
function shape(c,fill='white'){const forms=[`<circle cx="12" cy="12" r="7" fill="${fill}"/>`,`<path d="m12 2 10 10-10 10L2 12Z" fill="${fill}"/>`,`<path d="m12 3 10 18H2Z" fill="${fill}"/>`,`<path d="M9 2h6v7h7v6h-7v7H9v-7H2V9h7Z" fill="${fill}"/>`];return `<svg viewBox="0 0 24 24" aria-hidden="true">${forms[c]}</svg>`;}
function person(color,id=0){const skin=['#f3c6a3','#a96749','#d49974','#f6d5ba'][id%4],hair=['#392b34','#60434a','#342e41','#a57851'][id%4];return `<span class="person" data-person="${id}" data-color="${color}" aria-label="${names[color]} yolcu" style="--delay:-${id%7*.4}s"><svg viewBox="0 0 32 46" aria-hidden="true"><ellipse cx="16" cy="43" rx="11" ry="2.5" fill="#12244420"/><path class="leg-left" d="M12 32v8l-3 1" fill="none" stroke="#2c385c" stroke-width="4.5" stroke-linecap="round"/><path class="leg-right" d="M21 32v8l3 1" fill="none" stroke="#2c385c" stroke-width="4.5" stroke-linecap="round"/><g class="body"><path d="M8 23q0-6 8-6t8 6v11H8Z" fill="${colors[color]}" stroke="#152b4e24"/><path class="arm" d="m9 22-4 9" stroke="${colors[color]}" stroke-width="5" stroke-linecap="round"/><path d="m23 22 4 9" stroke="${colors[color]}" stroke-width="5" stroke-linecap="round"/><circle cx="5" cy="32" r="2.5" fill="${skin}"/><circle cx="27" cy="32" r="2.5" fill="${skin}"/><path d="M10 21v9" stroke="#fff" stroke-opacity=".18" stroke-width="2" stroke-linecap="round"/><rect class="phone-prop" x="4" y="23" width="5" height="8" rx="1" fill="#33485b" stroke="#bfe3ee" stroke-width="1"/><g class="head"><ellipse cx="16" cy="12" rx="8" ry="9" fill="${skin}"/><path d="M8 12Q5 2 15 2q12-1 10 11l-4-6q-4 3-9 1Z" fill="${hair}"/><circle cx="13" cy="12" r="1" fill="#342e41"/><circle cx="20" cy="12" r="1" fill="#342e41"/><path d="M14 16q2 2 4 0" fill="none" stroke="#975e55" stroke-width="1"/></g><svg x="11" y="23" width="11" height="11" viewBox="0 0 24 24">${shape(color,color===2?'#584718':'white').replace(/^<svg[^>]*>|<\/svg>$/g,'')}</svg></g></svg><i class="mood-bubble" hidden></i></span>`;}
function carSvg(c,dir=c.dir,filled=0,parked=false){
 const uid='vehicle-'+(++svgSerial),paint=colors[c.color];
 const h=c.capacity===6?136:102,angle=angles[dir],horizontal='EW'.includes(dir),vw=horizontal?h:52,vh=horizontal?52:h;
 const seats=Array.from({length:c.capacity},(_,i)=>{const x=i%2?29:13,y=41+Math.floor(i/2)*20;return `<g data-seat="${i}"><rect x="${x-2}" y="${y-3}" width="14" height="17" rx="4" fill="${i<filled?'#d1d6e7':'#c3cee6'}" stroke="#18294b" stroke-width="1.4"/><path d="M${x} ${y+9}h9" stroke="#e6eeff" stroke-width="2"/>${i<filled?`<ellipse cx="${x+5}" cy="${y+4}" rx="5.2" ry="6.5" fill="${colors[c.color]}"/><circle cx="${x+5}" cy="${y+1}" r="4.6" fill="#efb893"/><path d="M${x+1} ${y}q4-6 8 0" stroke="#453444" stroke-width="2.5" fill="none"/>${filled===c.capacity&&i===filled-1?`<path class="seat-wave" d="M${x+8} ${y+5}l4-5" stroke="#efb893" stroke-width="2.3" stroke-linecap="round"/>`:""}`:''}</g>`;}).join('');
 const roof=parked?`<g class="vehicle-roof"><rect x="10" y="38" width="32" height="${h-61}" rx="7" fill="${paint}"/><rect x="10" y="38" width="32" height="${h-61}" rx="7" fill="url(#${uid}-light)"/><path d="M12 42v${h-73}" stroke="#ffffff80" stroke-width="2"/><path class="direction-arrow" d="M26 ${h/2-12} 14 ${h/2+1}h7v18h10V${h/2+1}h7Z" fill="white" stroke="#14213a60" stroke-width="1" stroke-linejoin="round"/><path d="M11 ${h-24}h30l-3 8H14Z" fill="#22394f"/><path d="M15 ${h-22}h19" stroke="#8fc8e0" stroke-width="2"/></g>`:'';
 return `<svg viewBox="0 0 ${vw} ${vh}" aria-hidden="true"><defs><linearGradient id="${uid}-light" x1="0" x2="1" y1="0" y2=".3"><stop stop-color="#fff" stop-opacity=".55"/><stop offset=".35" stop-color="#fff" stop-opacity=".07"/><stop offset=".7" stop-color="#14213a" stop-opacity=".07"/><stop offset="1" stop-color="#14213a" stop-opacity=".4"/></linearGradient></defs><g transform="translate(${vw/2} ${vh/2}) rotate(${angle}) translate(-26 ${-h/2})"><rect x="0" y="23" width="9" height="19" rx="3" fill="#101b32"/><rect x="43" y="23" width="9" height="19" rx="3" fill="#101b32"/><rect x="0" y="${h-32}" width="9" height="18" rx="3" fill="#101b32"/><rect x="43" y="${h-32}" width="9" height="18" rx="3" fill="#101b32"/><rect x="6" y="6" width="44" height="${h-6}" rx="11" fill="#233049"/><rect x="4" y="2" width="44" height="${h-7}" rx="11" fill="${colors[c.color]}" stroke="#ffffff50" stroke-width="1"/><rect x="4" y="2" width="44" height="${h-7}" rx="11" fill="url(#${uid}-light)"/><path d="M9 17v${h-34}" stroke="#ffffff40" stroke-width="3" stroke-linecap="round"/><rect x="10" y="6" width="8" height="4" rx="2" fill="#fff9cf"/><rect x="34" y="6" width="8" height="4" rx="2" fill="#fff9cf"/>${parked?'':`<path d="m21 21 5-6 5 6m-5-6v12" stroke="${c.color===2?'#755b20':'white'}" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`}<rect x="9" y="32" width="34" height="${h-46}" rx="7" fill="#24324f"/><path d="M9 31h34l-3 6H12Z" fill="#a6e0f2"/><path d="M14 32h24" stroke="#e6fbff" stroke-width="2"/>${parked?roof:seats}<path d="M12 ${h-9}h7m14 0h7" stroke="#b82744" stroke-width="3" stroke-linecap="round"/><svg x="21" y="${h-18}" width="10" height="10" viewBox="0 0 24 24">${shape(c.color,c.color===2?'#6a5015':'#fff').replace(/^<svg[^>]*>|<\/svg>$/g,'')}</svg></g></svg>`;
}
function renderDistrict(){const d=district();$('app').dataset.district=d.id;$('district-name').textContent=d.name+' · '+level().difficulty;$('district-decor').innerHTML=sceneSvg(d.id);}
function sceneSvg(id){const art={mahalle:'<path d="M5 22V10L17 2l12 8v12M34 22V8l11-6 11 6v14"/><path d="M13 22v-8h8v8M40 11h10v6H40"/>',sahil:'<path d="M1 19q8-6 16 0t16 0 16 0 16 0M8 23q8-6 16 0t16 0 16 0"/><path d="M26 15V1l13 12H26M17 15h28l-5 5H23Z"/>',pazar:'<path d="M5 9h52l-5-7H10ZM10 10v13h42V10M16 14h12v9M35 14h12v7"/><path d="M15 3v6m10-6v6m10-6v6m10-6v6"/>',festival:'<path d="M2 2q30 15 60 0M7 5l5 9 4-6m7 2 5 9 5-8m7-1 7 7 3-10"/><path d="M21 25v-8m23 8v-8"/>',havalimani:'<path d="m2 14 24-3 11-9h7l-7 9 20 2v4l-20 1 7 7h-7l-11-7-24-1ZM48 3h12M50 6h8"/>'};return `<svg viewBox="0 0 64 28" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${art[id]}</g></svg>`;}
function clearFeedback(id,before){const l=level(),opened=state.parked.filter(n=>E.blockers(l,before,n).length&&!E.blockers(l,state,n).length);if(!opened.length)return;for(const n of opened){const c=E.car(l,n),el=document.createElement('i');el.className='scene-effect road-open';el.style.cssText=`left:${c.x/l.width*100}%;top:${c.y/l.height*100}%;width:${c.w/l.width*100}%;height:${c.h/l.height*100}%`;$('parking').append(el);animate(el,[{opacity:0},{opacity:1,offset:.2},{opacity:0}],1200,epoch,'ease-out').then(()=>el.remove());}message(opened.length===1?'Bir aracın yolu açıldı.':opened.length+' aracın yolu açıldı.');soundCue('clear');}
function stopAudio(){for(const node of audioNodes){try{node.stop();}catch(_){}}audioNodes.clear();}
function soundCue(kind){const notes={engine:[[105,.22,'triangle',0]],arrive:[[440,.09,'sine',0],[550,.1,'sine',.1]],seat:[[640,.07,'sine',0]],full:[[523,.1,'sine',0],[659,.1,'sine',.12],[784,.15,'sine',.24]],leave:[[390,.12,'sine',0]],clear:[[700,.06,'sine',0],[880,.08,'sine',.08]],win:[[523,.15,'sine',0],[659,.15,'sine',.16],[784,.15,'sine',.32],[1046,.25,'sine',.5]]};if(document.hidden)return;for(const [f,t,w,delay]of notes[kind]||[])tone(f,t,w,delay);}
function message(text,notice=false){$('message').textContent=text;$('message').classList.toggle('notice',notice);}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:5,levelUid:level().uid,log,completedUids:levels.filter((_,i)=>completed[i]).map(l=>l.uid),seen,speed,sound}));}catch(_){}}
function act(action,paint=true){const before=state;const r=E.transition(level(),state,action);if(!r.ok)return r;state=r.state;log.push(action);save();if(paint){render();if(action.type==='clear')clearFeedback(action.id,before);}return r;}
function finishInstant(){
 for(const b of [...state.bays].filter(Boolean)){if(b.phase==='driving'){if(state.exiting.includes(b.id))act({type:'clear',id:b.id},false);act({type:'arrive',id:b.id},false);}else if(b.phase==='leaving')act({type:'leave',id:b.id},false);}
 let slot;while((slot=E.nextBoard(level(),state))>=0){const id=state.bays[slot].id;act({type:'board',id},false);if(state.bays[slot]?.phase==='leaving')act({type:'leave',id},false);}
}
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('renk-parking-v041')||'null');if(!d||![4,5].includes(d.version))return;const uid=d.version===5?d.levelUid:'lot-'+(d.index+1),position=levels.findIndex(l=>l.uid===uid),done=new Set(d.version===5?d.completedUids||[]:(d.completed||[]).flatMap((v,i)=>v?['lot-'+(i+1)]:[]));completed=levels.map(l=>done.has(l.uid));seen=d.seen===true;speed=speedModes.some(m=>m.value===d.speed)?d.speed:1;sound=d.sound===true;if(position<0){index=0;log=[];state=E.initial(level());return;}index=position;state=E.replay(level(),d.log);log=d.log;finishInstant();}catch(_){log=[];state=E.initial(level());}}
function layoutLot(){renderDistrict();$('finish-card').hidden=true;celebrated=false;const l=level();zoomed=false;$('markings').innerHTML=l.cars.map(c=>`<div class="parking-spot ${c.dir}" style="left:${c.x/l.width*100}%;top:${c.y/l.height*100}%;width:${c.w/l.width*100}%;height:${c.h/l.height*100}%"><span>${String(c.id+1).padStart(2,'0')}</span></div>`).join('')+Array.from({length:Math.ceil(l.height/4)},(_,i)=>`<span class="zone" style="top:${i*4/l.height*100+2}%">${String.fromCharCode(65+i)} BLOK</span>`).join('');$('lot-viewport').scrollTop=0;$('lot-viewport').scrollLeft=0;queueHead=-1;fitLot();}
// Use the visual viewport, not a height breakpoint; browser bars can change it.
function fitLot(){
 const v=$('lot-viewport'),l=level();if(!v.clientWidth||!v.clientHeight)return;
 const fit=Math.max(8,Math.min((v.clientWidth-18)/l.width,(v.clientHeight-36)/l.height,46));
 const cell=zoomed?Math.max(44,fit*1.45):fit,w=Math.floor(cell*l.width),h=Math.floor(cell*l.height);
 $('parking').style.width=w+'px';$('parking').style.height=h+'px';$('lot-world').style.width=w+'px';
 $('overview').textContent=zoomed?'Tüm park −':'Yakınlaştır +';$('overview').setAttribute('aria-label',zoomed?'Otoparkın tamamını göster':'Otoparkı yakınlaştır');$('overview').setAttribute('aria-pressed',String(zoomed));
 $('view-label').textContent=zoomed?'Yakın görünüm · iki yönde kaydır':'Parkın tamamı · araca dokun';$('lot-position').textContent='';
 v.setAttribute('aria-label',zoomed?'Yakın otopark görünümü, iki yönde kaydırılabilir':'Otoparkın tamamı, araçlara dokunarak oynanabilir');
}
function resizeGame(){
 cancelAnimationFrame(layoutFrame);layoutFrame=requestAnimationFrame(()=>{const visual=window.visualViewport,height=visual&&visual.scale===1?visual.height:innerHeight;document.documentElement.style.setProperty('--app-height',Math.floor(height)+'px');fitLot();if(state)renderCrowd();});
}
function renderSpeed(){const mode=speedModes.find(m=>m.value===speed);$('speed').querySelector('small').textContent=mode.label;$('speed').querySelector('span').textContent=mode.icon;$('speed').setAttribute('aria-label','Hareket hızı: '+mode.label);$('speed').dataset.speed=mode.label;document.documentElement.style.setProperty('--motion-rate',speed);}
function queuePassenger(color,i){return `<div class="queue-place${i===0?' next-passenger':''}" role="listitem" aria-label="${i+1}. sırada, ${names[color]}"><span class="queue-number" aria-hidden="true">${i+1}</span>${person(color,state.head+i)}</div>`;}
function renderCrowd(advance=false){
 const ground=document.querySelector('.crowd-ground'),style=getComputedStyle(ground),w=ground.clientWidth,h=ground.clientHeight;
 if(!w||!h)return;
 for(const a of queueAnimations)a.cancel();queueAnimations.clear();
 const old=new Map((crowdLevel===index?[...$('queue').querySelectorAll('.queue-standing')]:[]).map(el=>[+el.querySelector('.person').dataset.person,{el,x:parseFloat(el.style.left),y:parseFloat(el.style.top),row:+el.dataset.row}]));
 const rows=+style.getPropertyValue('--queue-rows')||3,ph=parseFloat(style.getPropertyValue('--crowd-height'))||28;
 const cols=Math.max(6,Math.min(12,Math.floor((w-44)/28)+1)),step=(w-48)/(cols-1),bottom=h-13,top=ph+3,dy=(bottom-top)/(rows-1);
 const remaining=level().queue.slice(state.head,state.head+cols*rows),ys=Array.from({length:rows},(_,row)=>bottom-row*dy);
 const move=advance&&crowdLayout?.w===w&&crowdLayout?.h===h&&!fast&&!reduced;
 crowdLayout={w,h};crowdLevel=index;let path=`M24 ${bottom+10}V${bottom}H${w-24}`,arrows='';
 for(let row=1;row<rows;row++){const right=row%2===1,edge=right?w-7:7,x=right?w-24:24,prev=ys[row-1],y=ys[row];path+=`Q${edge} ${prev} ${edge} ${(prev+y)/2}Q${edge} ${y} ${x} ${y}H${right?24:w-24}`;arrows+=`<path class="queue-flow" d="M${edge-3} ${(prev+y)/2-2}l3 4 3-4"/>`;}
 $('queue-track').setAttribute('viewBox',`0 0 ${w} ${h}`);
 $('queue-track').innerHTML=`<path class="queue-rail-shadow" d="${path}"/><path class="queue-rail" d="${path}"/><path class="queue-paving" d="${path}"/>${arrows}`;
 const jobs=[],fragment=document.createDocumentFragment(),token=epoch;
 remaining.forEach((color,i)=>{const id=state.head+i,row=Math.floor(i/cols),col=i%cols,x=24+(row%2?cols-1-col:col)*step,y=ys[row],prev=old.get(id),el=prev?.el||document.createElement('div');
  el.className='queue-standing'+(i===0?' next-passenger':'');el.setAttribute('role','listitem');el.dataset.order=i+1;el.dataset.row=row;el.style.cssText=`left:${x}px;top:${y}px;z-index:${rows-row}`;el.setAttribute('aria-label',`${i+1}. sırada, ${names[color]}`);
  if(!prev)el.innerHTML=person(color,id)+'<span class="queue-number" aria-hidden="true"></span>';
  el.querySelector('.queue-number').textContent=i+1;el.querySelector('.person').classList.remove('walking-out');fragment.append(el);
  if(move&&prev){let frames=[{left:prev.x+'px',top:prev.y+'px'}];
   if(prev.row!==row){const edge=x<w/2?7:w-7,mid=(prev.y+y)/2;for(let j=1;j<12;j++){const t=j/12,q=t<.5?t*2:(t-.5)*2,u=1-q,ax=t<.5?prev.x:edge,ay=t<.5?prev.y:mid,bx=edge,by=t<.5?prev.y:y,cx=t<.5?edge:x,cy=t<.5?mid:y;frames.push({left:(u*u*ax+2*u*q*bx+q*q*cx)+'px',top:(u*u*ay+2*u*q*by+q*q*cy)+'px',offset:t});}}
   frames.push({left:x+'px',top:y+'px'});el.classList.add('queue-walking');el.dataset.facing=row%2?'right':'left';
   jobs.push(animate(el,frames,620,token,'ease-in-out',queueAnimations).then(()=>{if(token===epoch)el.classList.remove('queue-walking');}));
  }else if(move){jobs.push(animate(el,[{opacity:0},{opacity:1}],620,token,'linear',queueAnimations));}
 });
 $('queue').replaceChildren(fragment);if(!remaining.length)$('queue').innerHTML='<span class="empty-queue">Herkes bindi ✓</span>';
 if(document.querySelector('.fly-person'))$('queue').querySelector('.person')?.classList.add('walking-out');
 $('next-passenger-label').textContent=remaining.length?'İlk yolcu: '+names[remaining[0]]:'Herkes bindi';
 $('queue').setAttribute('aria-label','Biniş sırası, en altta soldaki yolcudan başlayarak kıvrımlı tek sıra');
 queueMotion=Promise.all(jobs);updateMoods();
}
function render(){
 const l=level(),free=state.bays.filter(b=>!b).length;
 $('level-number').textContent=String(l.id).padStart(2,'0');$('level-title').textContent=l.title;$('departed').textContent=state.departed.length+' / '+l.cars.length;$('lot-count').textContent=state.parked.length+' araç parkta · '+l.queue.length+' yolcu';
 if(queueHead!==state.head){const advance=queueHead>=0&&state.head===queueHead+1;queueHead=state.head;renderCrowd(advance);}
 const remaining=l.queue.length-state.head;$('queue-count').textContent=remaining+' yolcu bekliyor';$('queue-count').setAttribute('aria-label',remaining+' yolcu bekliyor');$('queue-progress').style.width=state.head/l.queue.length*100+'%';$('free-slots').textContent=free?free+' yer boş':'3 yer dolu';
 $('bays').innerHTML=state.bays.map((b,i)=>{const c=b&&E.car(l,b.id);return `<div class="bay ${b?.phase==='driving'?'reserved ':''}${b?.phase==='leaving'?'leaving ':''}${c?.capacity===6?'long':''}" data-slot="${i}" role="img" aria-label="${b?names[c.color]+' araç, '+b.filled+'/'+c.capacity+' dolu, '+(b.phase==='driving'?'yolda':b.phase==='leaving'?'çıkıyor':'bekliyor'):'Boş durak yeri '+(i+1)}">${b?b.phase==='driving'?`<span class="slot-number" style="color:${colors[c.color]}">${shape(c.color,colors[c.color])}</span><span class="fill-label">Yolda</span>`:`<div class="bay-car" data-bay-car="${b.id}">${carSvg(c,'N',b.filled)}</div><span class="fill-label">${b.phase==='leaving'?'Çıkıyor':b.filled+' / '+c.capacity}</span>`:`<span class="slot-number">${i+1}</span>`}</div>`;}).join('');
 $('cars').innerHTML=state.parked.map(id=>{const c=E.car(l,id),blocked=E.blockers(l,state,id).length;return `<button class="car" data-car="${id}" style="left:${c.x/l.width*100}%;top:${c.y/l.height*100}%;width:${c.w/l.width*100}%;height:${c.h/l.height*100}%" aria-label="${names[c.color]} araç ${id+1}, ${c.capacity} boş koltuk, ${directions[c.dir]}, önü ${blocked?'kapalı':'açık'}">${carSvg(c,c.dir,0,true)}</button>`;}).join('');
 $('app').classList.toggle('jammed',E.deadlocked(l,state));$('undo').disabled=!log.some(a=>a.type==='send');$('hint').disabled=E.won(l,state);renderSpeed();$('sound').querySelector('i').hidden=sound;$('sound').setAttribute('aria-label',sound?'Ses kapat':'Ses aç');
}
function updateMoods(){const elapsed=(Date.now()-levelStarted+moodOffset)/1000;let bubbleShown=false;for(const el of document.querySelectorAll('.person')){if(el.closest('.fly-person'))continue;const id=+el.dataset.person,mood=elapsed>36&&id%5===1?'toilet':elapsed>24&&id%3===2?'angry':id%7===3?'phone':id%9===5?'yawn':id%4===0?'wave':'idle';el.classList.remove('mood-wave','mood-angry','mood-toilet','mood-phone','mood-yawn');el.classList.add('mood-'+mood);el.dataset.mood=mood;const bubble=el.querySelector('.mood-bubble');const show=!bubbleShown&&Math.floor(elapsed/4)%3===0&&el.closest('#queue')&&(+el.closest('.queue-standing')?.dataset.order>6)&&!el.closest('.queue-walking')&&['toilet','angry'].includes(mood);bubble.hidden=!show;if(show)bubbleShown=true;bubble.textContent=mood==='toilet'?'WC?':mood==='angry'?'…!':'';el.setAttribute('aria-label',names[+el.dataset.color]+' yolcu'+(mood==='toilet'?', tuvaleti gelmiş':mood==='angry'?', beklemekten sıkılmış':''));}}
function showStatus(){if(E.won(level(),state))return;if(E.deadlocked(level(),state))message('Durak kilitlendi. Sıradaki '+names[level().queue[state.head]].toLocaleLowerCase('tr')+' yolcu için yer yok. Geri alıp yeni bir sıra dene.',true);else if(!E.active(level(),state))message(level().tip);}
function tone(frequency=520,length=.08,type='sine',delay=0){if(!sound||audioNodes.size>20)return;try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;audioContext=audioContext||new A();audioContext.resume().catch(()=>{});const o=audioContext.createOscillator(),g=audioContext.createGain(),at=audioContext.currentTime+delay;o.type=type;o.frequency.setValueAtTime(frequency,at);if(type==='triangle')o.frequency.exponentialRampToValueAtTime(frequency*1.35,at+length);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(type==='triangle'?.012:.03,at+.015);g.gain.exponentialRampToValueAtTime(.001,at+length);o.connect(g);g.connect(audioContext.destination);audioNodes.add(o);o.onended=()=>{audioNodes.delete(o);o.disconnect();g.disconnect();};o.start(at);o.stop(at+length+.02);}catch(_){}}
const center=el=>{const r=el.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2};};
async function animate(el,frames,ms,token,easing='linear',group){if(token!==epoch)return false;if(!el.animate)return true;const a=el.animate(frames,{duration:duration(ms),easing,fill:'forwards'});if(!fast&&!reduced)a.playbackRate=speed;animations.add(a);group?.add(a);if(nativePaused)a.pause();try{await a.finished;}catch(_){return false;}finally{animations.delete(a);group?.delete(a);a.cancel();}return token===epoch;}
function ghost(c,x,y,w,h,filled=0,local=false){const el=document.createElement('div');el.className='ghost-car'+(local?' local':'');el.style.cssText=`left:${x-w/2}px;top:${y-h/2}px;width:${w}px;height:${h}px`;el.innerHTML=carSvg(c,'N',filled,local);(local?$('exit-layer'):document.body).append(el);return el;}
function cancelMotion(){epoch++;for(const a of animations)a.cancel();animations.clear();queueAnimations.clear();queueMotion=Promise.resolve();stopAudio();$('finish-card').hidden=true;celebrated=false;document.querySelectorAll('.ghost-car,.fly-person,.scene-effect').forEach(el=>el.remove());boarding=false;departures.clear();roadTail=Promise.resolve();}
async function drive(id,token){
 const c=E.car(level(),id),parking=$('parking'),cell=parking.clientWidth/level().width,world=$('lot-world'),origin={x:parking.offsetLeft+(c.x+c.w/2)*cell,y:parking.offsetTop+(c.y+c.h/2)*cell},w=cell*.84,h=cell*Math.max(c.w,c.h)*.88;
 const edge={x:origin.x,y:origin.y};if(c.dir==='N')edge.y=-h/2;else if(c.dir==='S')edge.y=world.clientHeight+h/2;else if(c.dir==='W')edge.x=-h/2;else edge.x=world.clientWidth+h/2;
 const g=ghost(c,origin.x,origin.y,w,h,0,true),distance=Math.hypot(edge.x-origin.x,edge.y-origin.y);
 if(!await animate(g,[{transform:`rotate(${angles[c.dir]}deg)`},{transform:`translate(${edge.x-origin.x}px,${edge.y-origin.y}px) rotate(${angles[c.dir]}deg)`}],Math.max(950,distance/125*1000),token,'cubic-bezier(.4,0,.65,1)')){g.remove();return;}g.remove();act({type:'clear',id});
 // A shared approach lane prevents vehicles crossing each other at the curb.
 const previous=roadTail;let release;roadTail=new Promise(resolve=>release=resolve);await previous;
 try{
  if(token!==epoch)return;const slot=state.bays.findIndex(b=>b?.id===id);if(slot<0)return;
  const road=document.querySelector('.road').getBoundingClientRect(),target=center(document.querySelector(`[data-slot="${slot}"] .slot-number`)),from={x:road.left-35,y:road.top+road.height/2};
  const probe=document.createElement('div');probe.className='bay-car';const bayEl=document.querySelector(`[data-slot="${slot}"]`);bayEl.classList.toggle('long',c.capacity===6);bayEl.append(probe);const box=probe.getBoundingClientRect();target.x=box.left+box.width/2;target.y=box.top+box.height/2;probe.remove();
  const car=ghost(c,from.x,from.y,box.width,box.height);const scale=1;
  const frames=[{transform:'rotate(90deg)',easing:'ease-in'},{transform:`translate(${target.x-from.x-24}px,0) rotate(90deg)`,offset:.64,easing:'ease-in-out'},{transform:`translate(${target.x-from.x}px,-22px) rotate(0deg)`,offset:.84,easing:'ease-out'},{transform:`translate(${target.x-from.x}px,${target.y-from.y}px) rotate(0deg) scale(${scale})`}];
  const ok=await animate(car,frames,Math.max(1800,(target.x-from.x+90)/120*1000),token);car.remove();if(!ok)return;
  act({type:'arrive',id});soundCue('arrive');pump(token);
 }finally{release();}
}
async function boardOne(slot,token){
 await queueMotion;if(token!==epoch)return false;
 const bay=state.bays[slot];if(!bay)return false;const id=bay.id,c=E.car(level(),id),source=$('queue').querySelector('.person'),target=document.querySelector(`[data-bay-car="${id}"] [data-seat="${bay.filled}"]`);if(!source||!target)return false;
 const from=center(source),to=center(target),box=document.querySelector(`[data-bay-car="${id}"]`).getBoundingClientRect(),walkY=center(document.querySelector('.walkway')).y,door={x:box.right+7,y:box.top+box.height*.38};
 const el=document.createElement('div');el.className='fly-person';el.style.left=from.x-15+'px';el.style.top=from.y-21+'px';el.innerHTML=person(c.color,state.head);document.body.append(el);source.classList.add('walking-out');
 const marker=document.createElement('i');marker.className='scene-effect door-light';marker.style.cssText=`left:${door.x-4}px;top:${door.y-7}px`;document.body.append(marker);
 let ok=await animate(el,[{transform:'translate(0,0) scale(.78)'},{transform:`translate(0,${walkY-from.y}px) scale(.78)`,offset:.22},{transform:`translate(${door.x-from.x}px,${walkY-from.y}px) scale(.75)`,offset:.72},{transform:`translate(${door.x-from.x}px,${door.y-from.y}px) scale(.7)`}],1050+slot*160,token,'ease-in-out');
 if(ok){el.classList.add('stepping-in');ok=await animate(el,[{transform:`translate(${door.x-from.x}px,${door.y-from.y}px) scale(.7)`},{transform:`translate(${to.x-from.x}px,${to.y-from.y}px) scale(.34)`}],330,token,'ease-out');}
 marker.remove();el.remove();if(!ok)return false;
 act({type:'board',id});soundCue(state.bays[slot]?.phase==='leaving'?'full':'seat');
 const seat=document.querySelector(`[data-bay-car="${id}"] [data-seat="${bay.filled}"]`);if(seat)animate(seat,[{opacity:.35},{opacity:1}],320,token,'ease-out');
 return true;
}
async function depart(id,token){
 if(departures.has(id))return;departures.add(id);const slot=state.bays.findIndex(b=>b?.id===id),c=E.car(level(),id),bay=document.querySelector(`[data-slot="${slot}"]`),carEl=bay.querySelector('.bay-car'),from=center(carEl),carBox=carEl.getBoundingClientRect();
 const road=document.querySelector('.road').getBoundingClientRect(),dy=road.top+road.height/2-from.y,g=ghost(c,from.x,from.y,carBox.width,carBox.height,c.capacity);
 const ready=document.createElement('span');ready.className='scene-effect ready-badge';ready.textContent='Dolu ✓';bay.append(ready);await animate(ready,[{opacity:0,transform:'translate(-50%,3px)'},{opacity:1,transform:'translate(-50%,0)'},{opacity:0,transform:'translate(-50%,-4px)'}],650,token,'ease-in-out');ready.remove();if(token!==epoch){g.remove();return;}
 const ok=await animate(g,[{transform:'rotate(0deg)',easing:'ease-in'},{transform:`translate(0,${dy-18}px) rotate(0deg)`,offset:.35,easing:'ease-in-out'},{transform:`translate(23px,${dy}px) rotate(90deg)`,offset:.55,easing:'ease-in'},{transform:`translate(${road.right-from.x+65}px,${dy}px) rotate(90deg)`}],2400,token);g.remove();if(token!==epoch)return;departures.delete(id);if(!ok)return;act({type:'leave',id});soundCue('leave');pump(token);finishCheck();
}
async function pump(token=epoch){
 if(token!==epoch)return;for(const b of state.bays.filter(Boolean))if(b.phase==='leaving')depart(b.id,token);
 if(boarding)return;boarding=true;
 try{let slot;while(token===epoch&&(slot=E.nextBoard(level(),state))>=0){if(!await boardOne(slot,token))break;for(const b of state.bays.filter(Boolean))if(b.phase==='leaving')depart(b.id,token);}}
 finally{if(token===epoch){boarding=false;finishCheck();}}
}
function finishCheck(){if(E.won(level(),state)){if($('overlay').hidden)complete();return;}showStatus();}
function indicateBlock(id,blocked){const el=document.querySelector(`[data-car="${id}"]`),dir=E.car(level(),id).dir,delta={N:[0,-4],S:[0,4],E:[4,0],W:[-4,0]}[dir];if(el)animate(el,[{transform:'translate(0,0)'},{transform:`translate(${delta[0]}px,${delta[1]}px)`,offset:.4},{transform:'translate(0,0)'}],420,epoch,'ease-in-out');const other=blocked[0];document.querySelector(`[data-car="${other}"]`)?.classList.add('obstacle');message('Önü kapalı. '+names[E.car(level(),other).color]+' araç yolu açınca çıkabilir.',true);tone(180);const token=epoch;setTimeout(()=>{if(token!==epoch)return;document.querySelectorAll('.bump,.obstacle').forEach(el=>el.classList.remove('bump','obstacle'));},1600);}
function dispatch(id){if(!$('overlay').hidden)return;const r=act({type:'send',id});if(!r.ok){if(r.reason==='blocked')indicateBlock(id,r.blockedBy);else if(r.reason==='full')message(E.active(level(),state)?'Üç yer de ayrılmış. Bir araç perondan çıkınca yer açılacak.':'Durak dolu. Son aracı geri alıp sıradaki yolcuya yer aç.',true);return r;}
 message(names[E.car(level(),id).color]+' araç yolda. Boş yer varsa başka bir araç da gönderebilirsin.');soundCue('engine');drive(id,epoch);return r;}
function openModal(html){focused=document.activeElement;$('modal-content').innerHTML=html;$('overlay').hidden=false;$('app').inert=true;($('modal-content').querySelector('button')||$('close-modal')).focus();updateMoods();}
function closeModal(){if($('overlay').hidden)return;$('overlay').hidden=true;$('app').inert=false;(focused?.isConnected?focused:$('level-menu')).focus();if(E.won(level(),state)&&!celebrated)complete();}
function help(first=false){openModal(`<div class="eyebrow">HOŞ GELDİN · ACELE YOK</div><h2 id="modal-title">Şehrin yolu<br>senden sorulur.</h2><div class="rule"><b>1</b><span>Araca dokun. <strong>Önü açıksa</strong> ok yönünde çıkar.</span></div><div class="rule"><b>2</b><span>Perona en yakın sıranın solundaki 1 numaralı yolcu kendi rengindeki araca biner. <strong>Dolan araç ayrılır.</strong></span></div><div class="rule"><b>3</b><span>Üç peron var. Araçlar hareket ederken <strong>diğerlerini de gönderebilirsin.</strong></span></div><p>Otoparkın tamamı ekranda. Yakınlaştır ile büyüt; Tüm park ile geri dön. Parkta büyük okları izle. Peronda araçların içi açılır; boş koltukları sayabilirsin. Hız düğmesi Sakin, Normal ve Hızlı arasında geçer.</p><p class="mini-note">Yolcular bazen söylenir, bazen tuvalet arar. Bunlar yalnızca hareket: puan, ceza veya süre sınırı yok.</p><div class="chips"><span class="chip">Ücretsiz geri al</span><span class="chip">3 renk + şekiller</span><span class="chip">Yavaş hareket</span></div><button class="primary" data-action="start">${first?'Otoparka gir →':'Oyuna dön →'}</button>`);}
function queueDetails(){openModal(`<div class="eyebrow">ÖNDEN ARKAYA · SOLDAN SAĞA</div><h2 id="modal-title">${level().queue.length-state.head} yolcu bekliyor.</h2><p>1 numara önce biner. Numaraları soldan sağa, sonra alt satırdan takip et. Öndeki yolcunun aracı yoksa sıra bekler.</p><div class="queue-list" role="list" aria-label="Bütün yolcular, biniş sırasıyla">${level().queue.slice(state.head).map(queuePassenger).join('')||'Herkes bindi.'}</div><div class="legend">${names.slice(0,Math.max(...level().queue)+1).map((n,i)=>`<span>${shape(i,colors[i])}${n}</span>`).join('')}</div><button class="primary" data-action="close">Oyuna dön →</button>`);}
function levelButton(l,i){return `<button data-level="${i}" class="${completed[i]?'done ':''}${i===index?'current':''}" aria-label="Bölüm ${l.id}, ${l.title}">${String(l.id).padStart(2,'0')}<small>${completed[i]?'✓':l.difficulty||l.cars.length+' araç'}</small></button>`;}
function chapterGrid(){const c=chapters[mapPage],d=districts.find(d=>d.id===c.district);$('chapter-select').value=mapPage;$('chapter-prev').disabled=mapPage===0;$('chapter-next').disabled=mapPage===chapters.length-1;$('chapter-content').innerHTML=`<section class="district-card campaign-chapter" data-district="${d.id}"><div class="district-title"><span aria-hidden="true">${d.icon}</span><div><h3>${c.label}</h3><p>${levels[c.start].difficulty} rotalar · acele yok</p></div><b>${completed.slice(c.start,c.end).filter(Boolean).length}/${c.end-c.start}</b></div><div class="levels-grid">${levels.slice(c.start,c.end).map((l,i)=>levelButton(l,c.start+i)).join('')}</div></section>`;}
function levelMenu(){mapPage=pageFor(index);const done=completed.filter(Boolean).length;openModal(`<div class="eyebrow">${done} / ${levels.length} DURAK TAMAMLANDI</div><h2 id="modal-title">Şehir rotası</h2><div class="campaign-progress" role="progressbar" aria-label="Tamamlanan bölümler" aria-valuenow="${done}" aria-valuemin="0" aria-valuemax="${levels.length}"><i style="width:${done/levels.length*100}%"></i></div><button class="continue-route" data-action="close">Bölüm ${index+1} · Oyuna dön →</button><div class="chapter-controls"><button id="chapter-prev" data-action="chapter-prev" aria-label="Önceki bölüm grubu">‹</button><select id="chapter-select" aria-label="Bölüm grubu">${chapters.map((c,i)=>`<option value="${i}">${completed.slice(c.start,c.end).filter(Boolean).length===c.end-c.start?'✓ ':''}${c.label}</option>`).join('')}</select><button id="chapter-next" data-action="chapter-next" aria-label="Sonraki bölüm grubu">›</button></div><form id="level-jump"><label for="level-jump-number">Bölüme git</label><input id="level-jump-number" type="number" inputmode="numeric" min="1" max="${levels.length}" required placeholder="1–${levels.length}" aria-label="Bölüm numarası"><button type="submit">Git →</button></form><div id="chapter-content"></div><p class="mini-note">İlerlemen otomatik kaydedilir. Dilediğin bölümü deneyebilirsin. Bölümler küçük adımlarla zorlaşır. İpucu ve geri alma her zaman ücretsizdir.</p>`);chapterGrid();}
function overview(){zoomed=!zoomed;fitLot();$('lot-viewport').scrollTop=0;$('lot-viewport').scrollLeft=0;message(zoomed?'Yakın görünüm açık. Parkı kaydırabilir, Tüm park ile geri dönebilirsin.':'Otoparkın tamamı ekranda. Araçlara buradan dokunarak oynayabilirsin.');}
function reset(i){cancelMotion();index=i;state=E.initial(level());log=[];levelStarted=Date.now();moodOffset=0;layoutLot();save();render();showStatus();}
function undo(){let last=log.length-1;while(last>=0&&log[last].type!=='send')last--;if(last<0)return;cancelMotion();log=log.slice(0,last);state=E.replay(level(),log);finishInstant();queueHead=-1;save();render();message('Son gönderdiğin araç geri döndü. Önceki araçlar perondaki işlemlerini tamamladı.');}
function hint(){if(E.active(level(),state)){message('İpucunu araçlar yerleşince hesaplayabilirim. Bu sırada araç göndermeye devam edebilirsin.');return;}const plan=E.solve(level(),state,12000);if(!plan.path){message(plan.exhausted?'Bu konum için ipucu bulunamadı. Son hamleyi geri almayı deneyebilirsin.':'Bu sırayla çözüm kalmadı. Son aracı geri al.',true);return;}const id=plan.path[0];if(id===undefined)return;const el=document.querySelector(`[data-car="${id}"]`);el?.classList.add('hinted');if(el&&zoomed){const v=$('lot-viewport'),r=el.getBoundingClientRect(),vr=v.getBoundingClientRect();v.scrollTo({top:v.scrollTop+r.top-vr.top-v.clientHeight/2+r.height/2,behavior:reduced?'instant':'smooth'});}message(names[E.car(level(),id).color]+' araç işaretlendi. Çözüm için güvenli bir sonraki hamle.',true);}
function complete(){
 if(celebrated)return;celebrated=true;completed[index]=true;save();renderDistrict();
 const d=chapters[pageFor(index)],next=index<levels.length-1,finished=levels.slice(d.start,d.end).filter((_,i)=>completed[d.start+i]).length;
 $('finish-card').innerHTML=`<span class="finish-stamp" aria-hidden="true">✓</span><h2>Park açıldı!</h2><p>${level().queue.length} yolcu yerine ulaştı. ${d.label+': '+finished+' / '+(d.end-d.start)+' durak tamamlandı.'}</p><div><button class="primary" data-action="${next?'next':'levels'}">${next?'Sıradaki durak →':'Şehir haritası →'}</button><button class="finish-map" data-action="levels" aria-label="Şehir haritası">⌂</button></div>`;
 $('finish-card').hidden=false;animate($('finish-card'),[{opacity:0,transform:'translateY(15px)'},{opacity:1,transform:'translateY(0)'}],650,epoch,'ease-out');soundCue('win');message('Bütün yollar açıldı. Hazır olduğunda sıradaki durağa geçebilirsin.');
 if(!reduced&&!fast)for(let i=0;i<12;i++){const dot=document.createElement('i');dot.className='scene-effect confetti';dot.style.cssText=`left:${15+i*6}%;top:30%;--confetti:${colors[i%4]}`;$('lot-viewport').append(dot);animate(dot,[{opacity:0,transform:'translateY(0) rotate(0deg)'},{opacity:1,offset:.2},{opacity:0,transform:`translateY(${80+i%4*12}px) rotate(${160+i*45}deg)`}],1100,epoch,'ease-out').then(()=>dot.remove());}
}
$('cars').addEventListener('click',event=>{const el=event.target.closest('[data-car]');if(el)dispatch(+el.dataset.car);});
$('undo').addEventListener('click',undo);$('hint').addEventListener('click',hint);$('restart').addEventListener('click',()=>{if(!log.length){reset(index);return;}openModal('<div class="eyebrow">AYNI OTOPARK, YENİ PLAN</div><h2 id="modal-title">Baştan başlayalım mı?</h2><p>Araçlar ve sıra aynı kalır. Bu bölümdeki hamlelerin sıfırlanır.</p><button class="primary" data-action="retry">Yeniden başlat</button><button class="secondary" data-action="close">Oyuna dön</button>');});
$('speed').addEventListener('click',()=>{const current=speedModes.findIndex(m=>m.value===speed);speed=speedModes[(current+1)%speedModes.length].value;for(const a of animations)if(!fast&&!reduced)a.playbackRate=speed;save();renderSpeed();message(speedModes.find(m=>m.value===speed).label+' hız açık. Hareket hızı değişti; araç sırası aynı.');});
$('sound').addEventListener('click',()=>{sound=!sound;if(!sound)stopAudio();save();render();if(sound)soundCue('arrive');});$('help').addEventListener('click',()=>help());$('queue-info').addEventListener('click',queueDetails);$('overview').addEventListener('click',overview);$('level-menu').addEventListener('click',levelMenu);
$('lot-viewport').addEventListener('scroll',()=>{if(!zoomed)return;const progress=$('lot-viewport').scrollTop/Math.max(1,$('lot-world').clientHeight-$('lot-viewport').clientHeight);$('lot-position').textContent=Math.round(progress*100)+'%';});
$('close-modal').addEventListener('click',()=>{seen=true;save();closeModal();});
function handleAction(event){const b=event.target.closest('button');if(!b)return;if(b.dataset.level!==undefined){const i=+b.dataset.level;if(Number.isInteger(i)&&i>=0&&i<levels.length){closeModal();reset(i);}return;}switch(b.dataset.action){case'start':seen=true;save();closeModal();break;case'close':closeModal();break;case'next':closeModal();reset(Math.min(index+1,levels.length-1));break;case'retry':closeModal();reset(index);break;case'levels':levelMenu();break;case'chapter-prev':mapPage=Math.max(0,mapPage-1);chapterGrid();break;case'chapter-next':mapPage=Math.min(chapters.length-1,mapPage+1);chapterGrid();break;}}
$('modal-content').addEventListener('click',handleAction);
$('modal-content').addEventListener('change',event=>{if(event.target.id==='chapter-select'){mapPage=+event.target.value;chapterGrid();}});
$('modal-content').addEventListener('submit',event=>{if(event.target.id!=='level-jump')return;event.preventDefault();const n=+$('level-jump-number').value;if(Number.isInteger(n)&&n>=1&&n<=levels.length){closeModal();reset(n-1);}});$('finish-card').addEventListener('click',handleAction);
document.addEventListener('keydown',event=>{if($('overlay').hidden)return;if(event.key==='Escape'){event.preventDefault();seen=true;save();closeModal();}if(event.key==='Tab'){const buttons=[...$('overlay').querySelectorAll('button:not(:disabled),select,input')],first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
window.ParkingNative={pause(){nativePaused=true;save();stopAudio();for(const a of animations)a.pause();},resume(){nativePaused=false;for(const a of animations)a.play();resizeGame();},back(){if(!$('overlay').hidden){seen=true;save();closeModal();return true;}save();return false;}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)window.ParkingNative.pause();else window.ParkingNative.resume();});
document.documentElement.style.setProperty('--app-height',Math.floor(window.visualViewport?.height||innerHeight)+'px');
load();state=state||E.initial(level());layoutLot();render();showStatus();
addEventListener('resize',resizeGame);window.visualViewport?.addEventListener('resize',resizeGame);if(window.ResizeObserver)new ResizeObserver(fitLot).observe($('lot-viewport'));resizeGame();setInterval(updateMoods,4000);if(!seen)help(true);else if(E.won(level(),state))complete();
if(testMode)window.ParkingTest={E,levels,get:()=>({index,state:E.copy(state),log:E.copy(log),busy:E.active(level(),state)||boarding,speed,audioActive:audioNodes.size}),load:i=>{closeModal();reset(i);},dispatch,undo,close:closeModal,solve:()=>E.solve(level(),state),storageKey:KEY,moods:ms=>{moodOffset=ms;updateMoods();}};
})();
