(function(root){const routes=[
  {
    "id": 19,
    "title": "Tek koridor",
    "district": "mahalle",
    "focus": "Öndeki aracı çıkar, arkasındaki zinciri aç.",
    "tip": "Öndeki aracı çıkar, arkasındaki zinciri aç.",
    "width": 8,
    "height": 8,
    "cars": [
      {
        "id": 0,
        "x": 0,
        "y": 0,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 1,
        "x": 0,
        "y": 2,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 2,
        "x": 0,
        "y": 4,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 3,
        "x": 3,
        "y": 0,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 4,
        "x": 3,
        "y": 2,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 5,
        "x": 3,
        "y": 4,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 6,
        "x": 6,
        "y": 0,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 7,
        "x": 6,
        "y": 2,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 8,
        "x": 6,
        "y": 4,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 9,
        "x": 1,
        "y": 0,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 10,
        "x": 1,
        "y": 3,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 11,
        "x": 1,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 1,
        "capacity": 4
      }
    ],
    "queue": [
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      1,
      1,
      1,
      1,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0
    ],
    "solution": [
      0,
      1,
      3,
      4,
      6,
      7,
      9,
      2,
      5,
      8,
      10,
      11
    ],
    "trap": [
      0,
      3,
      6
    ],
    "sampleWins": 13,
    "sampleRuns": 160
  },
  {
    "id": 20,
    "title": "Dört çıkış",
    "district": "sahil",
    "focus": "Dört yöne bak; doğru zincirden başla.",
    "tip": "Dört yöne bak; doğru zincirden başla.",
    "width": 8,
    "height": 8,
    "cars": [
      {
        "id": 0,
        "x": 1,
        "y": 0,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 1,
        "x": 1,
        "y": 2,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 2,
        "x": 1,
        "y": 4,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 3,
        "x": 6,
        "y": 1,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 4,
        "x": 4,
        "y": 1,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 5,
        "x": 2,
        "y": 1,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 6,
        "x": 6,
        "y": 6,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 7,
        "x": 6,
        "y": 4,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 8,
        "x": 6,
        "y": 2,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 9,
        "x": 0,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "W",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 10,
        "x": 2,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "W",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 11,
        "x": 4,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "W",
        "color": 1,
        "capacity": 4
      }
    ],
    "queue": [
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      2,
      1,
      1,
      2,
      2,
      2,
      2,
      1,
      1,
      2,
      2,
      1,
      1,
      0,
      0,
      2,
      2,
      0,
      0,
      2,
      2,
      0,
      0,
      2,
      2,
      0,
      0,
      2,
      2,
      1,
      1,
      0,
      0,
      1,
      1,
      0,
      0
    ],
    "solution": [
      0,
      1,
      3,
      4,
      6,
      7,
      9,
      10,
      2,
      5,
      8,
      11
    ],
    "trap": [
      0,
      3,
      6
    ],
    "sampleWins": 25,
    "sampleRuns": 160
  },
  {
    "id": 21,
    "title": "Koltuk hesabı",
    "district": "pazar",
    "focus": "Dört ve altı koltuğu, sıranın devamıyla birlikte düşün.",
    "tip": "Dört ve altı koltuğu, sıranın devamıyla birlikte düşün.",
    "width": 8,
    "height": 8,
    "cars": [
      {
        "id": 0,
        "x": 0,
        "y": 0,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 1,
        "x": 0,
        "y": 2,
        "w": 1,
        "h": 3,
        "dir": "N",
        "color": 0,
        "capacity": 6
      },
      {
        "id": 2,
        "x": 0,
        "y": 5,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 3,
        "x": 3,
        "y": 0,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 4,
        "x": 3,
        "y": 2,
        "w": 1,
        "h": 3,
        "dir": "N",
        "color": 1,
        "capacity": 6
      },
      {
        "id": 5,
        "x": 3,
        "y": 5,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 6,
        "x": 6,
        "y": 0,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 7,
        "x": 6,
        "y": 2,
        "w": 1,
        "h": 3,
        "dir": "N",
        "color": 2,
        "capacity": 6
      },
      {
        "id": 8,
        "x": 6,
        "y": 5,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 9,
        "x": 1,
        "y": 0,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 10,
        "x": 1,
        "y": 3,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 11,
        "x": 1,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 1,
        "capacity": 4
      }
    ],
    "queue": [
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      2,
      1,
      1,
      2,
      2,
      1,
      1,
      2,
      2,
      1,
      1,
      2,
      2,
      1,
      1,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      1,
      1,
      0,
      0
    ],
    "solution": [
      0,
      1,
      3,
      4,
      6,
      7,
      9,
      2,
      5,
      8,
      10,
      11
    ],
    "trap": [
      0,
      3,
      6
    ],
    "sampleWins": 19,
    "sampleRuns": 160
  },
  {
    "id": 22,
    "title": "Sahil molası",
    "district": "sahil",
    "focus": "Renk gruplarını takip et; rahat bir tur at.",
    "tip": "Renk gruplarını takip et; rahat bir tur at.",
    "width": 8,
    "height": 8,
    "cars": [
      {
        "id": 0,
        "x": 6,
        "y": 1,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 1,
        "x": 4,
        "y": 1,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 2,
        "x": 2,
        "y": 1,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 3,
        "x": 6,
        "y": 6,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 4,
        "x": 6,
        "y": 4,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 5,
        "x": 6,
        "y": 2,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 6,
        "x": 0,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "W",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 7,
        "x": 2,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "W",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 8,
        "x": 4,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "W",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 9,
        "x": 1,
        "y": 0,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 10,
        "x": 1,
        "y": 2,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 11,
        "x": 1,
        "y": 4,
        "w": 1,
        "h": 2,
        "dir": "N",
        "color": 1,
        "capacity": 4
      }
    ],
    "queue": [
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      2,
      2,
      2,
      2,
      0,
      0,
      0,
      0,
      2,
      2,
      2,
      2,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0
    ],
    "solution": [
      0,
      1,
      3,
      4,
      6,
      7,
      9,
      10,
      2,
      5,
      8,
      11
    ],
    "trap": [
      0,
      3,
      6
    ],
    "sampleWins": 30,
    "sampleRuns": 160
  },
  {
    "id": 23,
    "title": "Bir yer ayır",
    "district": "festival",
    "focus": "Açık her aracı gönderme; sıradakine peron bırak.",
    "tip": "Açık her aracı gönderme; sıradakine peron bırak.",
    "width": 8,
    "height": 8,
    "cars": [
      {
        "id": 0,
        "x": 6,
        "y": 0,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 1,
        "x": 4,
        "y": 0,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 2,
        "x": 2,
        "y": 0,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 3,
        "x": 6,
        "y": 3,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 4,
        "x": 4,
        "y": 3,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 5,
        "x": 2,
        "y": 3,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 6,
        "x": 6,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 7,
        "x": 4,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 8,
        "x": 2,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 9,
        "x": 7,
        "y": 1,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 10,
        "x": 4,
        "y": 1,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 11,
        "x": 1,
        "y": 1,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 1,
        "capacity": 4
      }
    ],
    "queue": [
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      2,
      1,
      2,
      1,
      2,
      1,
      2,
      2,
      1,
      2,
      1,
      2,
      1,
      2,
      1,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      1,
      0,
      1,
      0,
      1,
      0
    ],
    "solution": [
      0,
      1,
      3,
      4,
      6,
      7,
      9,
      2,
      5,
      8,
      10,
      11
    ],
    "trap": [
      0,
      3,
      6
    ],
    "sampleWins": 23,
    "sampleRuns": 160
  },
  {
    "id": 24,
    "title": "Son bağlantı",
    "district": "havalimani",
    "focus": "Uzun araçlar ve kesişen çıkışları birlikte planla.",
    "tip": "Uzun araçlar ve kesişen çıkışları birlikte planla.",
    "width": 8,
    "height": 8,
    "cars": [
      {
        "id": 0,
        "x": 6,
        "y": 0,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 1,
        "x": 3,
        "y": 0,
        "w": 3,
        "h": 1,
        "dir": "E",
        "color": 0,
        "capacity": 6
      },
      {
        "id": 2,
        "x": 1,
        "y": 0,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 3,
        "x": 6,
        "y": 3,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 4,
        "x": 3,
        "y": 3,
        "w": 3,
        "h": 1,
        "dir": "E",
        "color": 1,
        "capacity": 6
      },
      {
        "id": 5,
        "x": 1,
        "y": 3,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 6,
        "x": 6,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 1,
        "capacity": 4
      },
      {
        "id": 7,
        "x": 3,
        "y": 6,
        "w": 3,
        "h": 1,
        "dir": "E",
        "color": 2,
        "capacity": 6
      },
      {
        "id": 8,
        "x": 1,
        "y": 6,
        "w": 2,
        "h": 1,
        "dir": "E",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 9,
        "x": 7,
        "y": 1,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 2,
        "capacity": 4
      },
      {
        "id": 10,
        "x": 4,
        "y": 1,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 0,
        "capacity": 4
      },
      {
        "id": 11,
        "x": 1,
        "y": 1,
        "w": 1,
        "h": 2,
        "dir": "S",
        "color": 1,
        "capacity": 4
      }
    ],
    "queue": [
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      2,
      1,
      2,
      1,
      2,
      1,
      2,
      1,
      1,
      2,
      1,
      2,
      1,
      2,
      1,
      2,
      1,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      1,
      0,
      1,
      0,
      1,
      0
    ],
    "solution": [
      0,
      1,
      3,
      4,
      6,
      7,
      9,
      2,
      5,
      8,
      10,
      11
    ],
    "trap": [
      0,
      3,
      6
    ],
    "sampleWins": 22,
    "sampleRuns": 160
  }
];if(typeof module!=='undefined'&&module.exports)module.exports=routes;else root.PARKING_LEVELS.push(...routes);})(typeof window!=='undefined'?window:globalThis);
